# Generated by Django 4.1.7 on 2023-02-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=16)),
            ],
        ),
    ]
